version: "3"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: "mongodb"
    ports:
      - 27017:27017

  phonebook-backend:
    image: phonebook-backend
    container_name: phonebook-backend
    ports:
      - 8081:8081
    links:
      - mongodb

  phonebook-frontend:
    image: phonebook-frontend
    container_name: phonebook-frontend
    ports:
      - 80:80
    links:
      - phonebook-backend
    depends_on: 
      - phonebook-backend

